apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify
  namespace: barrux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notify
  template:
    metadata:
      labels:
        app: notify
    spec:
      containers:
      - name: notify
        image: notify:v1
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: notifyservice
  namespace: barrux
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: notify
  type: LoadBalancer
